version: '2.4'
services:
        tiago:
                build:
                        context: .
                        dockerfile: docker/Dockerfile
                        target: tiago
                runtime: nvidia
                environment:
                        ROS_IP: $ROS_IP
                        ROS_HOSTNAME: $ROS_HOSTNAME
                        ROS_MASTER_URI: $ROS_MASTER_URI
                        DISPLAY: $DISPLAY
                        QT_X11_NO_MITSHM: '1'
                        NVIDIA_VISIBLE_DEVICES: all
                        NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
                network_mode: host
                privileged: true
                stdin_open: true
                volumes:
                        - /tmp/.X11-unix:/tmp/.X11-unix
                        - $HOME/.Xauthority:/root/.Xauthority
                        - ./rviz_config:/opt/ros/melodic/share/rviz/config/
                command: bash -c "source /root/catkin_ws/devel/setup.bash && roslaunch tiago_gazebo tiago_gazebo.launch public_sim:=true robot:=steel world:=empty && rviz"
